import os
import pandas as pd
import smtplib
from email.message import EmailMessage

print("BULK EMAIL SYSTEM STARTED")

# ================= CONFIG =================
SENDER_EMAIL = "pandeyvipul645@gmail.com"
APP_PASSWORD = "xjjd eqtm fcdz mxir"

DATA_FILE = "output/final_rankings.xlsx"
GRADECARD_DIR = "output/gradecards"
CERTIFICATE_DIR = "output/certificates"

SEND_GRADECARD = True
SEND_CERTIFICATE = True

# ================= LOAD DATA =================
df = pd.read_excel(DATA_FILE)
df.columns = df.columns.str.strip()

df["Email"] = df["Email"].astype(str).str.strip().str.lower()
df["Name"] = df["Name"].astype(str).str.strip()

# ================= FUNCTIONS =================
def safe_name(name):
    return name.strip().replace(" ", "_")


def send_email(receiver_email, student_name, gradecard_path=None, certificate_path=None):
    msg = EmailMessage()

    msg["Subject"] = "🎓 LIET Bootcamp Training Report & Certificate"
    msg["From"] = SENDER_EMAIL
    msg["To"] = receiver_email

    body = f"""
Dear {student_name},

Greetings from Lloyd Institute of Engineering & Technology.

Please find attached your LIET Bootcamp Training performance documents.

Regards,
LIET Training Team
"""

    html = f"""
<!DOCTYPE html>
<html>
<head>
<style>
body {{
    font-family: Arial, Helvetica, sans-serif;
    background: #f4f6f9;
    padding: 30px;
}}
.container {{
    max-width: 700px;
    margin: auto;
    background: #ffffff;
    border-radius: 16px;
    overflow: hidden;
    box-shadow: 0 10px 30px rgba(0,0,0,0.15);
}}
.header {{
    background: linear-gradient(135deg,#003366,#0077cc,#00bcd4);
    color: white;
    padding: 35px 25px;
    text-align: center;
}}
.header h1 {{
    margin: 0;
    font-size: 30px;
}}
.header p {{
    margin-top: 10px;
    font-size: 16px;
}}
.content {{
    padding: 35px;
    color: #333333;
    line-height: 1.8;
}}
.highlight {{
    background: #eef7ff;
    border-left: 6px solid #0077cc;
    padding: 18px;
    border-radius: 10px;
    margin: 22px 0;
}}
.docs {{
    background: #f9fbff;
    padding: 18px;
    border-radius: 12px;
    border: 1px solid #e0ecff;
}}
.docs li {{
    padding: 8px 0;
}}
.button {{
    display: inline-block;
    padding: 14px 28px;
    background: #0077cc;
    color: white !important;
    text-decoration: none;
    border-radius: 8px;
    margin-top: 22px;
    font-weight: bold;
}}
.footer {{
    background: #003366;
    color: white;
    padding: 25px;
    text-align: center;
    font-size: 14px;
}}
</style>
</head>

<body>
<div class="container">

    <div class="header">
        <h1>🎓 LIET Bootcamp Training</h1>
        <p>Official Performance Report & Certificate</p>
    </div>

    <div class="content">
        <h2>Dear {student_name},</h2>

        <p>
            Greetings from <b>Lloyd Institute of Engineering & Technology, Greater Noida.</b>
        </p>

        <p>
            Congratulations on successfully participating in the
            <b>LIET Bootcamp Training Program.</b>
        </p>

        <div class="highlight">
            <b>Your training performance documents have been generated successfully.</b>
        </div>

        <div class="docs">
            <h3>📄 Attached Documents</h3>
            <ul>
                {"<li>✅ Performance Gradecard</li>" if gradecard_path else ""}
                {"<li>🏆 Training Completion Certificate</li>" if certificate_path else ""}
            </ul>
        </div>

        <p>
            Please download the attached files and keep them safely for future academic and placement purposes.
        </p>

        <p>
            We appreciate your dedication and wish you continued success in your learning journey.
        </p>
        <p> student can visit the official student portal for more details and resources.</p>
        <p>loigin to the student portal using your registered email and password for all are same (Lloyd@2025).</p>
        <center>
            <a class="button" href="https://www.lloydcollege.in">Visit LIET Website</a>
        </center>
    </div>

    <div class="footer">
        <b>Lloyd Institute of Engineering & Technology</b><br>
        Greater Noida, Uttar Pradesh<br><br>
        📧 info@liet.in<br>
        🌐 www.lloydcollege.in<br><br>
        <i>This is an automated email generated by the LIET Smart ERP System.</i>
    </div>

</div>
</body>
</html>
"""

    msg.set_content(body)
    msg.add_alternative(html, subtype="html")

    attachments = []

    if gradecard_path and os.path.exists(gradecard_path):
        attachments.append(gradecard_path)

    if certificate_path and os.path.exists(certificate_path):
        attachments.append(certificate_path)

    if not attachments:
        print(f"No attachments found for {student_name}")
        return False

    for file_path in attachments:
        with open(file_path, "rb") as f:
            msg.add_attachment(
                f.read(),
                maintype="application",
                subtype="pdf",
                filename=os.path.basename(file_path)
            )

    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as smtp:
        smtp.login(SENDER_EMAIL, APP_PASSWORD)
        smtp.send_message(msg)

    return True


# ================= SEND BULK EMAILS =================
success = 0
failed = 0

for _, row in df.iterrows():
    try:
        name = row["Name"]
        email = row["Email"]

        if pd.isna(email) or email == "" or email == "nan":
            print(f"Skipping {name}: No email")
            failed += 1
            continue

        gradecard_path = None
        certificate_path = None

        if SEND_GRADECARD:
            gradecard_path = os.path.join(
                GRADECARD_DIR,
                f"{safe_name(name)}_gradecard.pdf"
            )

        if SEND_CERTIFICATE:
            certificate_path = os.path.join(
                CERTIFICATE_DIR,
                f"{safe_name(name)}_certificate.pdf"
            )

        sent = send_email(
            receiver_email=email,
            student_name=name,
            gradecard_path=gradecard_path,
            certificate_path=certificate_path
        )

        if sent:
            print(f"Sent to {name} - {email}")
            success += 1
        else:
            failed += 1

    except Exception as e:
        print(f"Failed for {row.get('Name', 'Unknown')}: {e}")
        failed += 1

print("BULK EMAIL COMPLETED")
print("Success:", success)
print("Failed:", failed)