import os
import re
import smtplib
import ssl
from email.message import EmailMessage


class Emailer:
    """
    LIET Smart ERP Email Sender

    Features:
    - PDF filename se document type auto-detect
    - Certificate aur Gradecard ke liye alag stylish email
    - Professional HTML template
    - Plain-text fallback
    - Attachment validation
    - Safe filename handling
    - Gmail SMTP SSL support
    """

    def __init__(self, sender_email, app_password):
        self.sender = str(sender_email).strip()
        self.password = str(app_password).strip()

        if not self.sender:
            raise ValueError("Sender email cannot be empty.")

        if not self.password:
            raise ValueError("Gmail app password cannot be empty.")

    # =====================================================
    # CLEAN TEXT
    # =====================================================
    @staticmethod
    def clean_text(value, default=""):
        if value is None:
            return default

        text = str(value).strip()

        if text.lower() in ["", "nan", "none", "null"]:
            return default

        return text

    # =====================================================
    # DOCUMENT TYPE DETECTION
    # =====================================================
    @staticmethod
    def detect_document_type(pdf_path):
        """
        Examples supported:

        Shreyanshi_Yadav_LIET-MLAI-046_certificate.pdf
        Akash_Kumar_Yadav_LIET-MLAI-054_gradecard.pdf
        """

        filename = os.path.basename(pdf_path)
        lowercase_filename = filename.lower()

        if "_certificate" in lowercase_filename:
            return {
                "type": "Certificate",
                "subject": "🏆 Congratulations! Your LIET Training Certificate is Ready",
                "document_title": "Training Completion Certificate",
                "heading": "Certificate of Completion",
                "header_subtitle": "Official ML & Agentic AI Bootcamp Certificate",
                "icon": "🏆",
                "accent_color": "#C69214",
                "accent_light": "#FFF7D6",
                "description": (
                    "Congratulations on successfully completing the "
                    "ML & Agentic AI Bootcamp Training Programme."
                ),
                "highlight_message": (
                    "Your official training completion certificate has "
                    "been generated and attached to this email."
                ),
                "attachment_label": "Training Certificate",
                "cta_text": "Open Student ERP"
            }

        if "_gradecard" in lowercase_filename:
            return {
                "type": "Gradecard",
                "subject": "📄 Your LIET Bootcamp Performance Gradecard",
                "document_title": "Performance Gradecard",
                "heading": "Bootcamp Performance Report",
                "header_subtitle": "Official Assessment and Performance Summary",
                "icon": "📄",
                "accent_color": "#0877C9",
                "accent_light": "#EAF6FF",
                "description": (
                    "Your ML & Agentic AI Bootcamp performance report "
                    "has been generated successfully."
                ),
                "highlight_message": (
                    "Your detailed assessment performance, rank, grade, "
                    "CGPA and attendance are available in the attached gradecard."
                ),
                "attachment_label": "Performance Gradecard",
                "cta_text": "View Student Dashboard"
            }

        return {
            "type": "Document",
            "subject": "📎 Your LIET Smart ERP Document",
            "document_title": "Student Document",
            "heading": "Official Student Document",
            "header_subtitle": "Generated by LIET Smart ERP",
            "icon": "📎",
            "accent_color": "#44546A",
            "accent_light": "#F1F4F7",
            "description": (
                "Your requested student document has been generated successfully."
            ),
            "highlight_message": (
                "Please find your official document attached to this email."
            ),
            "attachment_label": "Student Document",
            "cta_text": "Open Student ERP"
        }

    # =====================================================
    # EXTRACT VERIFICATION ID FROM FILE NAME
    # =====================================================
    @staticmethod
    def extract_verification_id(pdf_path):
        filename = os.path.basename(pdf_path)

        match = re.search(
            r"(LIET-MLAI-\d+)",
            filename,
            flags=re.IGNORECASE
        )

        if match:
            return match.group(1).upper()

        return "Not Available"

    # =====================================================
    # SAFE ATTACHMENT NAME
    # =====================================================
    @staticmethod
    def get_attachment_name(pdf_path):
        filename = os.path.basename(pdf_path)

        if not filename.lower().endswith(".pdf"):
            filename = f"{filename}.pdf"

        return filename

    # =====================================================
    # BUILD PLAIN TEXT EMAIL
    # =====================================================
    def build_plain_body(
        self,
        student_name,
        receiver_email,
        document_info,
        attachment_name,
        verification_id
    ):
        return f"""
Dear {student_name},

Greetings from Lloyd Institute of Engineering & Technology.

{document_info["description"]}

{document_info["highlight_message"]}

Attached Document:
{attachment_name}

Document Type:
{document_info["document_title"]}

Verification ID:
{verification_id}

Student ERP Login Details:
Email: {receiver_email}
Password: Lloyd@2025

Student ERP:
<a href="https://automated-erp-training-student.streamlit.app/" target="_blank">Access Student ERP</a>

Please download and keep this document safely for academic, internship and placement purposes.

Regards,
LIET Bootcamp Training Team
Lloyd Institute of Engineering & Technology
Greater Noida, Uttar Pradesh

This is an automated email generated by the LIET Smart ERP System.
"""

    # =====================================================
    # BUILD STYLISH HTML EMAIL
    # =====================================================
    def build_html_body(
        self,
        student_name,
        receiver_email,
        document_info,
        attachment_name,
        verification_id
    ):
        accent_color = document_info["accent_color"]
        accent_light = document_info["accent_light"]

        return f"""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <style>
        * {{
            box-sizing: border-box;
        }}

        body {{
            margin: 0;
            padding: 0;
            background-color: #eef2f7;
            font-family: Arial, Helvetica, sans-serif;
            color: #243447;
        }}

        .wrapper {{
            width: 100%;
            padding: 28px 12px;
            background-color: #eef2f7;
        }}

        .container {{
            width: 100%;
            max-width: 720px;
            margin: 0 auto;
            background-color: #ffffff;
            border-radius: 18px;
            overflow: hidden;
            box-shadow: 0 12px 35px rgba(25, 45, 75, 0.16);
            border: 1px solid #dfe7f0;
        }}

        .top-strip {{
            height: 8px;
            background: linear-gradient(
                90deg,
                #003366,
                {accent_color},
                #00a5c8
            );
        }}

        .header {{
            padding: 38px 28px 30px;
            text-align: center;
            color: #ffffff;
            background: linear-gradient(
                135deg,
                #003366 0%,
                {accent_color} 58%,
                #00a5c8 100%
            );
        }}

        .header-icon {{
            width: 70px;
            height: 70px;
            margin: 0 auto 14px;
            border-radius: 50%;
            background: rgba(255,255,255,0.18);
            border: 2px solid rgba(255,255,255,0.35);
            display: table;
        }}

        .header-icon span {{
            display: table-cell;
            vertical-align: middle;
            text-align: center;
            font-size: 34px;
        }}

        .header h1 {{
            margin: 0;
            font-size: 29px;
            line-height: 1.25;
            font-weight: 700;
        }}

        .header p {{
            margin: 10px 0 0;
            font-size: 15px;
            line-height: 1.6;
            color: rgba(255,255,255,0.93);
        }}

        .college-name {{
            margin-top: 12px;
            font-size: 13px;
            letter-spacing: 0.5px;
            font-weight: 700;
        }}

        .content {{
            padding: 34px 36px 30px;
        }}

        .greeting {{
            font-size: 23px;
            color: #16324f;
            margin: 0 0 14px;
        }}

        .intro {{
            font-size: 15px;
            line-height: 1.8;
            color: #425466;
            margin: 0 0 18px;
        }}

        .success-card {{
            background-color: {accent_light};
            border-left: 6px solid {accent_color};
            border-radius: 12px;
            padding: 18px 20px;
            margin: 22px 0;
        }}

        .success-card h3 {{
            margin: 0 0 8px;
            color: #17324d;
            font-size: 17px;
        }}

        .success-card p {{
            margin: 0;
            color: #425466;
            line-height: 1.65;
            font-size: 14px;
        }}

        .document-card {{
            margin: 22px 0;
            border: 1px solid #dce6ef;
            border-radius: 14px;
            overflow: hidden;
            background-color: #fbfdff;
        }}

        .document-card-header {{
            padding: 14px 18px;
            background-color: #f1f6fb;
            border-bottom: 1px solid #dce6ef;
            color: #16324f;
            font-weight: 700;
            font-size: 15px;
        }}

        .document-card-body {{
            padding: 18px;
        }}

        .file-row {{
            display: table;
            width: 100%;
        }}

        .file-icon {{
            display: table-cell;
            width: 54px;
            vertical-align: middle;
        }}

        .file-icon-box {{
            width: 44px;
            height: 44px;
            border-radius: 10px;
            background-color: {accent_light};
            color: {accent_color};
            font-size: 22px;
            text-align: center;
            line-height: 44px;
        }}

        .file-details {{
            display: table-cell;
            vertical-align: middle;
        }}

        .file-name {{
            font-weight: 700;
            font-size: 14px;
            color: #183b56;
            word-break: break-word;
        }}

        .file-type {{
            margin-top: 5px;
            color: #6b7c93;
            font-size: 12px;
        }}

        .verification-box {{
            margin-top: 16px;
            padding: 12px 15px;
            border-radius: 9px;
            background-color: #f7f9fc;
            border: 1px dashed #aab8c7;
            color: #4a5b6b;
            font-size: 13px;
        }}

        .verification-id {{
            color: {accent_color};
            font-weight: 700;
        }}

        .login-box {{
            margin: 22px 0;
            padding: 20px;
            background: linear-gradient(
                135deg,
                #fff8e6,
                #fffdf6
            );
            border-left: 6px solid #f0a500;
            border-radius: 12px;
        }}

        .login-box h3 {{
            margin: 0 0 13px;
            color: #493600;
            font-size: 17px;
        }}

        .login-row {{
            padding: 7px 0;
            font-size: 14px;
            color: #4a4a4a;
        }}

        .login-label {{
            font-weight: 700;
            color: #2b2b2b;
        }}

        .password-note {{
            margin-top: 12px;
            font-size: 12px;
            color: #7b6a3c;
        }}

        .button-wrapper {{
            text-align: center;
            margin: 26px 0 12px;
        }}

        .button {{
            display: inline-block;
            padding: 14px 26px;
            margin: 6px;
            border-radius: 9px;
            text-decoration: none;
            font-size: 14px;
            font-weight: 700;
        }}

        .primary-button {{
            background-color: {accent_color};
            color: #ffffff !important;
        }}

        .secondary-button {{
            background-color: #ffffff;
            color: #003366 !important;
            border: 1px solid #9fb3c8;
        }}

        .notice {{
            margin-top: 22px;
            padding: 14px 16px;
            border-radius: 10px;
            background-color: #f7f9fc;
            color: #5d6b79;
            font-size: 13px;
            line-height: 1.65;
        }}

        .footer {{
            padding: 27px 24px;
            text-align: center;
            color: #ffffff;
            background-color: #003366;
        }}

        .footer-title {{
            font-size: 15px;
            font-weight: 700;
            margin-bottom: 8px;
        }}

        .footer-line {{
            font-size: 12px;
            line-height: 1.8;
            color: rgba(255,255,255,0.86);
        }}

        .footer-divider {{
            width: 55px;
            height: 2px;
            margin: 16px auto;
            background-color: {accent_color};
        }}

        .automated-note {{
            font-size: 11px;
            line-height: 1.6;
            color: rgba(255,255,255,0.72);
        }}

        @media only screen and (max-width: 600px) {{
            .wrapper {{
                padding: 14px 8px;
            }}

            .content {{
                padding: 26px 20px;
            }}

            .header {{
                padding: 30px 20px 25px;
            }}

            .header h1 {{
                font-size: 24px;
            }}

            .button {{
                display: block;
                margin: 10px 0;
            }}
        }}
    </style>
</head>

<body>
    <div class="wrapper">

        <div class="container">

            <div class="top-strip"></div>

            <div class="header">

                <div class="header-icon">
                    <span>{document_info["icon"]}</span>
                </div>

                <h1>{document_info["heading"]}</h1>

                <p>{document_info["header_subtitle"]}</p>

                <div class="college-name">
                    LLOYD INSTITUTE OF ENGINEERING & TECHNOLOGY
                </div>

            </div>

            <div class="content">

                <h2 class="greeting">
                    Dear {student_name},
                </h2>

                <p class="intro">
                    Greetings from
                    <b>Lloyd Institute of Engineering & Technology,
                    Greater Noida.</b>
                </p>

                <p class="intro">
                    {document_info["description"]}
                </p>

                <div class="success-card">

                    <h3>
                        {document_info["icon"]}
                        Your {document_info["document_title"]} is Ready
                    </h3>

                    <p>
                        {document_info["highlight_message"]}
                    </p>

                </div>

                <div class="document-card">

                    <div class="document-card-header">
                        Attached Document
                    </div>

                    <div class="document-card-body">

                        <div class="file-row">

                            <div class="file-icon">
                                <div class="file-icon-box">
                                    📎
                                </div>
                            </div>

                            <div class="file-details">

                                <div class="file-name">
                                    {attachment_name}
                                </div>

                                <div class="file-type">
                                    {document_info["attachment_label"]} · PDF Document
                                </div>

                            </div>

                        </div>

                        <div class="verification-box">
                            Verification ID:
                            <span class="verification-id">
                                {verification_id}
                            </span>
                        </div>

                    </div>

                </div>

                <div class="login-box">

                    <h3>
                        🎓 Student ERP Login Details
                    </h3>

                    <div class="login-row">
                        <span class="login-label">Email:</span>
                        {receiver_email}
                    </div>

                    <div class="login-row">
                        <span class="login-label">Password:</span>
                        Lloyd@2025
                    </div>

                    <div class="password-note">
                        For security, please change your password after your first login
                        whenever this option becomes available.
                    </div>

                </div>

                <div class="button-wrapper">

                    <a
                        class="button primary-button"
                        href="https://automated-erp-training-student.streamlit.app/"
                        target="_blank"
                    >
                        {document_info["cta_text"]}
                    </a>

                    <a
                        class="button secondary-button"
                        href="https://automated-erp-training-home.streamlit.app/"
                        target="_blank"
                    >
                        Visit LIET Website
                    </a>

                </div>

                <div class="notice">
                    Please download and keep this document safely for academic,
                    internship and placement purposes. The attached PDF contains
                    your unique verification information.
                </div>

            </div>

            <div class="footer">

                <div class="footer-title">
                    Lloyd Institute of Engineering & Technology
                </div>

                <div class="footer-line">
                    Greater Noida, Uttar Pradesh
                </div>

                <div class="footer-line">
                    https://automated-erp-training-home.streamlit.app/
                </div>

                <div class="footer-divider"></div>

                <div class="automated-note">
                    This is an automated email generated by the
                    LIET Smart ERP System.<br>
                    Please do not reply directly to this email.
                </div>

            </div>

        </div>

    </div>
</body>
</html>
"""

    # =====================================================
    # SEND PDF EMAIL
    # =====================================================
    def send_pdf(
        self,
        receiver_email,
        pdf_path,
        student_name,
        doc_type=None
    ):
        """
        doc_type is optional.

        Document type is automatically detected from filenames like:

        Shreyanshi_Yadav_LIET-MLAI-046_certificate.pdf
        Akash_Kumar_Yadav_LIET-MLAI-054_gradecard.pdf
        """

        receiver_email = self.clean_text(
            receiver_email
        )

        student_name = self.clean_text(
            student_name,
            "Student"
        )

        if not receiver_email:
            print(
                f"❌ Receiver email missing for {student_name}"
            )
            return False

        if not os.path.exists(pdf_path):
            print(
                f"❌ File not found: {pdf_path}"
            )
            return False

        if not os.path.isfile(pdf_path):
            print(
                f"❌ Invalid file path: {pdf_path}"
            )
            return False

        if not pdf_path.lower().endswith(".pdf"):
            print(
                f"❌ Only PDF files are supported: {pdf_path}"
            )
            return False

        document_info = self.detect_document_type(
            pdf_path
        )

        attachment_name = self.get_attachment_name(
            pdf_path
        )

        verification_id = self.extract_verification_id(
            pdf_path
        )

        msg = EmailMessage()

        msg["Subject"] = document_info["subject"]
        msg["From"] = self.sender
        msg["To"] = receiver_email

        plain_body = self.build_plain_body(
            student_name=student_name,
            receiver_email=receiver_email,
            document_info=document_info,
            attachment_name=attachment_name,
            verification_id=verification_id
        )

        html_body = self.build_html_body(
            student_name=student_name,
            receiver_email=receiver_email,
            document_info=document_info,
            attachment_name=attachment_name,
            verification_id=verification_id
        )

        msg.set_content(
            plain_body
        )

        msg.add_alternative(
            html_body,
            subtype="html"
        )

        try:
            with open(pdf_path, "rb") as pdf_file:
                pdf_data = pdf_file.read()

            msg.add_attachment(
                pdf_data,
                maintype="application",
                subtype="pdf",
                filename=attachment_name
            )

            ssl_context = ssl.create_default_context()

            with smtplib.SMTP_SSL(
                "smtp.gmail.com",
                465,
                context=ssl_context,
                timeout=45
            ) as smtp:

                smtp.login(
                    self.sender,
                    self.password
                )

                smtp.send_message(
                    msg
                )

            print(
                f"✅ {document_info['document_title']} sent successfully\n"
                f"   Student: {student_name}\n"
                f"   Email: {receiver_email}\n"
                f"   File: {attachment_name}\n"
                f"   Verification ID: {verification_id}"
            )

            return True

        except smtplib.SMTPAuthenticationError:
            print(
                "❌ Gmail authentication failed.\n"
                "Use a valid Gmail App Password, not your normal Gmail password."
            )
            return False

        except smtplib.SMTPRecipientsRefused:
            print(
                f"❌ Receiver email was refused: {receiver_email}"
            )
            return False

        except smtplib.SMTPException as error:
            print(
                f"❌ SMTP error for {student_name}: {error}"
            )
            return False

        except OSError as error:
            print(
                f"❌ File or network error for {student_name}: {error}"
            )
            return False

        except Exception as error:
            print(
                f"❌ Email failed for {student_name}: {error}"
            )
            return False


# =========================================================
# EXAMPLE USAGE
# =========================================================
if __name__ == "__main__":

    # Never upload or commit your real password to GitHub.
    # Use environment variables or Streamlit secrets.

    sender_email = os.getenv(
        "LIET_SENDER_EMAIL",
        ""
    )

    app_password = os.getenv(
        "LIET_APP_PASSWORD",
        ""
    )

    if not sender_email or not app_password:
        print(
            "Set LIET_SENDER_EMAIL and LIET_APP_PASSWORD "
            "environment variables before running this file."
        )

    else:
        emailer = Emailer(
            sender_email=sender_email,
            app_password=app_password
        )

        # Example:
        #
        # emailer.send_pdf(
        #     receiver_email="student@gmail.com",
        #     pdf_path=(
        #         "output/certificates/"
        #         "Shreyanshi_Yadav_LIET-MLAI-046_certificate.pdf"
        #     ),
        #     student_name="Shreyanshi Yadav"
        # )
        #
        # emailer.send_pdf(
        #     receiver_email="student@gmail.com",
        #     pdf_path=(
        #         "output/gradecards/"
        #         "Akash_Kumar_Yadav_LIET-MLAI-054_gradecard.pdf"
        #     ),
        #     student_name="Akash Kumar Yadav"
        # )

        print(
            "Emailer initialized successfully."
        )