import os
import smtplib
from email.message import EmailMessage


class Emailer:
    def __init__(self, sender_email, app_password):
        self.sender = sender_email
        self.password = app_password

    def send_pdf(self, receiver_email, pdf_path, student_name, doc_type="Gradecard"):
        msg = EmailMessage()

        if doc_type == "Certificate":
            subject = "🏆 Your LIET Training Certificate"
            document_title = "Training Completion Certificate"
        else:
            subject = "📄 Your LIET Bootcamp Report Card"
            document_title = "Performance Gradecard"

        msg["Subject"] = subject
        msg["From"] = self.sender
        msg["To"] = receiver_email

        plain_body = f"""
Dear {student_name},

Greetings from Lloyd Institute of Engineering & Technology.

Please find attached your {document_title}.

You can also access your academic details from the LIET Student ERP Portal.

Login Email: {receiver_email}
Password: Lloyd@2025

Regards,
LIET Bootcamp Training Team
"""

        html_body = f"""
<!DOCTYPE html>
<html>
<head>
<style>
body {{
    font-family: Arial, Helvetica, sans-serif;
    background: #f4f6f9;
    padding: 30px;
}}
.container {{
    max-width: 720px;
    margin: auto;
    background: #ffffff;
    border-radius: 16px;
    overflow: hidden;
    box-shadow: 0 10px 30px rgba(0,0,0,0.15);
}}
.header {{
    background: linear-gradient(135deg, #003366, #0077cc, #00bcd4);
    color: white;
    padding: 35px 25px;
    text-align: center;
}}
.header h1 {{
    margin: 0;
    font-size: 30px;
}}
.header p {{
    margin-top: 10px;
    font-size: 16px;
}}
.content {{
    padding: 35px;
    color: #333333;
    line-height: 1.8;
}}
.highlight {{
    background: #eef7ff;
    border-left: 6px solid #0077cc;
    padding: 18px;
    border-radius: 10px;
    margin: 22px 0;
}}
.docs {{
    background: #f9fbff;
    padding: 18px;
    border-radius: 12px;
    border: 1px solid #e0ecff;
}}
.login-box {{
    background: #fff8e6;
    border-left: 6px solid #ffb300;
    padding: 18px;
    border-radius: 10px;
    margin: 22px 0;
}}
.button {{
    display: inline-block;
    padding: 14px 28px;
    background: #0077cc;
    color: white !important;
    text-decoration: none;
    border-radius: 8px;
    margin: 10px;
    font-weight: bold;
}}
.footer {{
    background: #003366;
    color: white;
    padding: 25px;
    text-align: center;
    font-size: 14px;
}}
</style>
</head>

<body>
<div class="container">

    <div class="header">
        <h1>🎓 LIET Smart ERP</h1>
        <p>Official Bootcamp Training Report</p>
    </div>

    <div class="content">
        <h2>Dear {student_name},</h2>

        <p>
            Greetings from <b>Lloyd Institute of Engineering & Technology, Greater Noida.</b>
        </p>

        <p>
            Congratulations on successfully participating in the
            <b>Machine Learning & Agentic AI Bootcamp Training Program.</b>
        </p>

        <div class="highlight">
            <b>Your {document_title} has been generated successfully.</b>
        </div>

        <div class="docs">
            <h3>📎 Attached Document</h3>
            <ul>
                <li>✅ {document_title}</li>
            </ul>
        </div>

        <div class="login-box">
            <h3>🎓 Student ERP Login Details</h3>
            <p><b>Email:</b> {receiver_email}</p>
            <p><b>Password:</b> Lloyd@2025</p>
            <p>You can view your dashboard, analytics, downloads, AI mentor and academic progress from the Student ERP portal.</p>
        </div>

        <p>
            Please download and keep this document safely for academic, internship and placement purposes.
        </p>

        <center>
            <a class="button" href="https://training-performance-liet-erp-5udhv9x4s3ni8qdlzffxro.streamlit.app/">
                🎓 Open Student ERP
            </a>

            <a class="button" href="https://www.lloydcollege.in">
                🌐 Visit LIET Website
            </a>
        </center>
    </div>

    <div class="footer">
        <b>Lloyd Institute of Engineering & Technology</b><br>
        Greater Noida, Uttar Pradesh<br><br>
        📧 info@liet.in<br>
        🌐 www.lloydcollege.in<br><br>
        <i>This is an automated email generated by the LIET Smart ERP System.</i>
    </div>

</div>
</body>
</html>
"""

        msg.set_content(plain_body)
        msg.add_alternative(html_body, subtype="html")

        if not os.path.exists(pdf_path):
            print(f"❌ File not found: {pdf_path}")
            return False

        try:
            with open(pdf_path, "rb") as f:
                msg.add_attachment(
                    f.read(),
                    maintype="application",
                    subtype="pdf",
                    filename=os.path.basename(pdf_path)
                )

            with smtplib.SMTP_SSL("smtp.gmail.com", 465) as smtp:
                smtp.login(self.sender, self.password)
                smtp.send_message(msg)

            print(f"✅ {document_title} sent to {student_name} - {receiver_email}")
            return True

        except Exception as e:
            print(f"❌ Email failed for {student_name}: {e}")
            return False